# Generated by Django 2.2.10 on 2020-11-16 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_question', models.TextField(verbose_name='Вопрос')),
                ('question_type', models.IntegerField(choices=[(1, 'Ответ текстом'), (2, 'Ответ с выбором одного варианта'), (3, 'Ответ с выбором нескольких вариантов')], verbose_name='Тип вопроса')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Polls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_poll', models.CharField(db_index=True, max_length=128, verbose_name='Название опроса')),
                ('date_start', models.DateTimeField(verbose_name='Начало опроса')),
                ('date_finish', models.DateTimeField(verbose_name='Конец опроса')),
                ('description', models.TextField(default='', verbose_name='Описание')),
                ('question', models.ManyToManyField(blank=True, related_name='question_from_poll', to='poll.Questions', verbose_name='Вопросы')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
                'ordering': ['-date_start'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='poll.Questions')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('choice_text', models.CharField(blank=True, max_length=256, null=True, verbose_name='Ответ')),
                ('choice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choice', to='poll.Choice')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll', to='poll.Polls')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_from_answer', to='poll.Questions')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
