# Generated by Django 2.2.10 on 2020-11-16 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'Вариант', 'verbose_name_plural': 'Варианты'},
        ),
    ]
