# Generated by Django 2.2.10 on 2020-11-16 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20201116_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polls',
            name='question',
        ),
        migrations.AddField(
            model_name='questions',
            name='poll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_from_poll', to='poll.Polls', verbose_name='Вопросы'),
        ),
    ]
