# Generated by Django 2.2.10 on 2020-11-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20201116_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='poll',
        ),
        migrations.AddField(
            model_name='polls',
            name='question',
            field=models.ManyToManyField(blank=True, related_name='question_from_poll', to='poll.Questions', verbose_name='Вопросы'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='choice_text',
            field=models.CharField(default='', max_length=256, verbose_name='Ответ'),
        ),
    ]
